# Enable Powerlevel10k instant prompt. Should stay close to the top of ~/.zshrc.
# Initialization code that may require console input (password prompts, [y/n]
# confirmations, etc.) must go above this block; everything else may go below.
#if [[ -r "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh" ]]; then
  #source "${XDG_CACHE_HOME:-$HOME/.cache}/p10k-instant-prompt-${(%):-%n}.zsh"
#fi

# If you come from bash you might have to change your $PATH.
# export PATH=$HOME/bin:/usr/local/bin:$PATH

export PATH="$PATH:$GOBIN"

# Path to your oh-my-zsh installation.
export ZSH="/home/aadi/.oh-my-zsh"

# Set name of the theme to load --- if set to "random", it will
ZSH_THEME="bullet-train"

plugins=(
git
zsh-autosuggestions
zsh-syntax-highlighting 
sudo
web-search
copydir
copyfile
copybuffer
)

ZSH_WEB_SEARCH_ENGINES=(reddit "https://www.reddit.com/search/?q=")

export TERM=xterm-256color

source $ZSH/oh-my-zsh.sh

source ~/.specific

alias modz="vim ~/.zshrc"
alias srcz="source ~/.zshrc"

alias ls="lsd -la"
alias pac="sudo pacman -Sy"
alias update="sudo pacman -Syu"
alias rpac="sudo pacman -R"
alias pfind="sudo pacman -Q | grep"
alias aurlist="pacman -Qm"

alias big="figlet"

alias y="yay -Sy"
alias aur="yay -Ss"

alias rm="rm -rf"
alias wh="whereis"

# To customize prompt, run `p10k configure` or edit ~/.p10k.zsh.
# [[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh
